import { Seo } from '@/components/Seo';
import { useState } from 'react';
import { Navigate } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Download, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { ENTITIES, entityName } from '@/lib/entities';
import { LaunchpadShell, StatusBadge, IdeaDetails, LoadError, dateTime, money } from '@/components/launchpad/LaunchpadShared';
import { getReview, changeIdeaStatus, exportIdeas, LAUNCHPAD_STATUSES, type IdeaStatus, type IdeaSubmission, type ReviewFilters } from '@/services/launchpadService';
const empty: ReviewFilters={status:'',entity:'',from:'',to:'',search:''};
const selectClass='flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm';
function StatusEditor({ submission, onSaved }: { submission: IdeaSubmission; onSaved: () => Promise<void> }) {
  const [status,setStatus]=useState<IdeaStatus>(submission.status); const [busy,setBusy]=useState(false);
  const save=async()=>{ setBusy(true); try { await changeIdeaStatus(submission.id,status,submission.version); toast.success('Status updated'); await onSaved(); } catch(e) { toast.error(e instanceof Error?e.message:'Could not update status'); await onSaved(); } finally {setBusy(false);} };
  return <div className="flex gap-2"><select aria-label={`Status for ${submission.reference}`} className={`${selectClass} min-w-36`} value={status} onChange={e=>setStatus(e.target.value as IdeaStatus)} disabled={busy}>{Object.entries(LAUNCHPAD_STATUSES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><Button size="sm" className="h-10" disabled={busy||status===submission.status} onClick={save}>{busy?'Saving…':'Save'}</Button></div>;
}
export default function LaunchpadReviewPage({ panel = false }: { panel?: boolean }) {
  const {user}=useAuth();
  const panelUser = user?.role === 'admin' || user?.role === 'manager';
  const allowed = panel ? panelUser : user?.role === 'user' && user.canReviewLaunchpad;
  const client=useQueryClient();
  const [draft,setDraft]=useState<ReviewFilters>(empty); const [filters,setFilters]=useState<ReviewFilters>(empty); const [page,setPage]=useState(1); const [selected,setSelected]=useState<number|null>(null); const [exporting,setExporting]=useState(false);
  const result=useQuery({queryKey:['launchpad',user?.id,'review',filters,page],queryFn:()=>getReview(filters,page),enabled:!!allowed,refetchInterval:30000});
  const refresh=async()=>{await client.invalidateQueries({queryKey:['launchpad']});};
  const download=async()=>{setExporting(true);try{await exportIdeas(filters);}catch(e){toast.error(e instanceof Error?e.message:'Export failed');}finally{setExporting(false);}};
  if(!allowed) return <Navigate to={panelUser ? "/admin/launchpad" : "/launchpad"} replace/>;
  return <LaunchpadShell panel={panel}><Seo title="Review dashboard | LaunchPad" path={panel ? "/admin/launchpad" : "/launchpad/review"} description="Track and review LaunchPad ideas." /><header className="flex flex-wrap gap-4 items-start justify-between"><div><h1 className="font-display text-3xl font-bold">Review dashboard</h1><p className="text-muted-foreground mt-2">Ideas from across Iwosan, in one place.</p></div><div className="flex gap-2"><Button variant="outline" aria-label="Refresh submissions" onClick={()=>refresh()} disabled={result.isFetching}><RefreshCw className={`h-4 w-4 ${result.isFetching?'animate-spin':''}`}/></Button><Button onClick={download} disabled={exporting||result.isPending||!!result.error}><Download className="h-4 w-4 mr-2"/>{exporting?'Exporting…':'Export CSV'}</Button></div></header>
    <form className="rounded-2xl border p-5 space-y-4" onSubmit={e=>{e.preventDefault();setFilters({...draft});setPage(1);}}><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4"><div className="space-y-2"><Label htmlFor="review-search">Search</Label><Input id="review-search" placeholder="Name, email, reference or idea" maxLength={200} value={draft.search} onChange={e=>setDraft({...draft,search:e.target.value})}/></div><div className="space-y-2"><Label htmlFor="review-status">Status</Label><select id="review-status" className={selectClass} value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option value="">All statuses</option>{Object.entries(LAUNCHPAD_STATUSES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div><div className="space-y-2"><Label htmlFor="review-entity">Entity</Label><select id="review-entity" className={selectClass} value={draft.entity} onChange={e=>setDraft({...draft,entity:e.target.value})}><option value="">All entities</option>{ENTITIES.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}<option value="unassigned">Unassigned</option></select></div><div className="space-y-2"><Label htmlFor="review-from">Submitted from</Label><Input id="review-from" type="date" value={draft.from} onChange={e=>setDraft({...draft,from:e.target.value})}/></div><div className="space-y-2"><Label htmlFor="review-to">Submitted to</Label><Input id="review-to" type="date" min={draft.from||undefined} value={draft.to} onChange={e=>setDraft({...draft,to:e.target.value})}/></div><div className="flex gap-2 items-end"><Button type="submit">Apply filters</Button><Button type="button" variant="outline" onClick={()=>{setDraft(empty);setFilters(empty);setPage(1);}}>Clear</Button></div></div><p className="text-xs text-muted-foreground">Date ranges include the full end date in Lagos time. Counts and exports use the applied filters. Exports include all matching responses, across every page.</p></form>
    {result.isPending && <p role="status">Loading dashboard…</p>}{result.error && <LoadError error={result.error} retry={()=>result.refetch()}/>}
    {result.data && <><div className="grid grid-cols-2 lg:grid-cols-5 gap-3">{[['total','All matching'],...Object.entries(LAUNCHPAD_STATUSES)].map(([key,label])=><div key={key} className="rounded-2xl border bg-card p-5"><p className="text-xs text-muted-foreground">{label}</p><p className="text-3xl font-bold mt-2">{key==='total'?result.data.total:result.data.summary[key as IdeaStatus]}</p></div>)}</div>
      <section className="space-y-4"><h2 className="text-lg font-semibold">Submissions <span className="text-muted-foreground font-normal">({result.data.total})</span></h2>{!result.data.submissions.length && <p className="rounded-xl border border-dashed p-8 text-center text-muted-foreground">No submissions match these filters.</p>}
      {result.data.submissions.map(s=><article key={s.id} className="rounded-2xl border bg-card p-5 space-y-4"><div className="flex flex-wrap justify-between gap-3"><div><button className="text-sm font-semibold underline underline-offset-4" onClick={()=>setSelected(s.id)}>{s.reference}</button><p className="text-xs text-muted-foreground mt-1">{dateTime(s.submittedAt)}</p></div><StatusBadge status={s.status}/></div><p className="font-medium line-clamp-2 break-words">{s.answers.idea}</p><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div className="text-sm min-w-0"><p className="font-medium">{s.userName} · {entityName(s.userEntity)}</p><p className="text-muted-foreground break-all">{s.userEmail}</p><p className="text-muted-foreground mt-1">{s.answers.department} · {money(s.answers.funding)}</p></div><div className="flex flex-col sm:flex-row gap-2"><Button variant="outline" onClick={()=>setSelected(s.id)}>View response</Button><StatusEditor key={`${s.id}-${s.version}`} submission={s} onSaved={refresh}/></div></div></article>)}
      <div className="flex justify-between items-center gap-3"><Button variant="outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</Button><span className="text-sm text-muted-foreground">Page {page} of {Math.max(1,Math.ceil(result.data.total/result.data.pageSize))}</span><Button variant="outline" disabled={page*result.data.pageSize>=result.data.total} onClick={()=>setPage(p=>p+1)}>Next</Button></div></section></>}
    <IdeaDetails id={selected} onClose={()=>setSelected(null)}/>
  </LaunchpadShell>;
}
